"""initial migration

Revision ID: 4023f9a6c91c
Revises: 
Create Date: 2025-03-14 21:27:25.469053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4023f9a6c91c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('member_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'members', ['member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'member_id')
    # ### end Alembic commands ###
